# 03. Classification

Imports

In [104]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.metrics import mutual_info_score
from sklearn.feature_extraction import DictVectorizer
from sklearn.linear_model import LogisticRegression

from IPython.display import display

%matplotlib inline

In [47]:
df = pd.read_csv(
    "https://raw.githubusercontent.com/DataTalksClub/machine-learning-zoomcamp/main/cohorts/2026/data/course_lead_scoring_2026.csv"
)
df

         lead_source       industry  ... lead_score converted
0     organic_search     technology  ...       0.64         1
1       social_media     technology  ...       0.72         1
2           referral         retail  ...       0.58         1
3           paid_ads  manufacturing  ...       0.57         0
4           referral  manufacturing  ...       0.62         1
...              ...            ...  ...        ...       ...
4995  organic_search      education  ...       0.37         1
4996             NaN     technology  ...       0.51         0
4997  organic_search        finance  ...       0.75         1
4998        referral     technology  ...       0.79         1
4999        referral     technology  ...       0.99         1

[5000 rows x 9 columns]

Data preparation

In [48]:
df.dtypes

lead_source                     str
industry                        str
employment_status               str
location                        str
annual_income               float64
number_of_courses_viewed      int64
interaction_count             int64
lead_score                  float64
converted                     int64
dtype: object

In [49]:
df.isnull().sum()

lead_source                 148
industry                    240
employment_status           194
location                    208
annual_income               369
number_of_courses_viewed      0
interaction_count             0
lead_score                   35
converted                     0
dtype: int64

In [53]:
categorical = list(df.columns[df.dtypes == "str"])
numerical = list(df.columns.difference(categorical + ["converted"], sort=False))
display(categorical, numerical)

['lead_source', 'industry', 'employment_status', 'location']

['annual_income',
 'number_of_courses_viewed',
 'interaction_count',
 'lead_score']

In [54]:
df[categorical] = df[categorical].fillna("NA")
df[numerical] = df[numerical].fillna(0.0)
df.isnull().sum()

lead_source                 0
industry                    0
employment_status           0
location                    0
annual_income               0
number_of_courses_viewed    0
interaction_count           0
lead_score                  0
converted                   0
dtype: int64

## Question 1

In [71]:
df.industry.value_counts()

industry
technology       1173
retail            925
healthcare        840
finance           720
education         639
manufacturing     463
NA                240
Name: count, dtype: int64

Answer: technology

## Question 2

In [90]:
res = []

for n in numerical:
    res.append(df[numerical].corrwith(df[n]).to_dict())

corr_matrix = pd.DataFrame(res, index=numerical)
corr_matrix

                          annual_income  ...  lead_score
annual_income                  1.000000  ...    0.229496
number_of_courses_viewed       0.161300  ...    0.757204
interaction_count              0.122842  ...    0.915746
lead_score                     0.229496  ...    1.000000

[4 rows x 4 columns]

or

In [91]:
corr_matrix = df[numerical].corr()
corr_matrix

                          annual_income  ...  lead_score
annual_income                  1.000000  ...    0.229496
number_of_courses_viewed       0.161300  ...    0.757204
interaction_count              0.122842  ...    0.915746
lead_score                     0.229496  ...    1.000000

[4 rows x 4 columns]

Answer: interaction_count and lead_score

---

Split the data

In [92]:
df_full_train, df_test = train_test_split(df, test_size=0.2, random_state=42)
df_train, df_val = train_test_split(df_full_train, test_size=0.25, random_state=42)

In [96]:
y_full_train = df_full_train.converted.values
y_train = df_train.converted.values
y_val = df_val.converted.values
y_test = df_test.converted.values

len(y_full_train), len(y_train), len(y_val), len(y_test)

(4000, 3000, 1000, 1000)

In [97]:
del df_full_train["converted"]
del df_train["converted"]
del df_val["converted"]
del df_test["converted"]

## Question 3

In [103]:
for c in categorical:
    display(f"{c}: {round(mutual_info_score(df_train[c], y_train), 2)}")

'lead_source: 0.03'

'industry: 0.0'

'employment_status: 0.02'

'location: 0.0'

Answer: lead_source

## Question 4

In [107]:
df_train_dicts = df_train[categorical + numerical].to_dict(orient="records")
df_train_dicts

[{'lead_source': 'paid_ads',
  'industry': 'finance',
  'employment_status': 'employed',
  'location': 'asia',
  'annual_income': 65980.0,
  'number_of_courses_viewed': 2,
  'interaction_count': 3,
  'lead_score': 0.37},
 {'lead_source': 'events',
  'industry': 'finance',
  'employment_status': 'employed',
  'location': 'south_america',
  'annual_income': 71662.0,
  'number_of_courses_viewed': 0,
  'interaction_count': 0,
  'lead_score': 0.09},
 {'lead_source': 'referral',
  'industry': 'NA',
  'employment_status': 'employed',
  'location': 'asia',
  'annual_income': 40220.0,
  'number_of_courses_viewed': 2,
  'interaction_count': 5,
  'lead_score': 0.55},
 {'lead_source': 'organic_search',
  'industry': 'finance',
  'employment_status': 'employed',
  'location': 'north_america',
  'annual_income': 88352.0,
  'number_of_courses_viewed': 2,
  'interaction_count': 2,
  'lead_score': 0.45},
 {'lead_source': 'events',
  'industry': 'technology',
  'employment_status': 'employed',
  'location': 'north_america',
  'annual_income': 89316.0,
  'number_of_courses_viewed': 1,
  'interaction_count': 5,
  'lead_score': 0.0},
 {'lead_source': 'paid_ads',
  'industry': 'healthcare',
  'employment_status': 'self_employed',
  'location': 'europe',
  'annual_income': 55610.0,
  'number_of_courses_viewed': 2,
  'interaction_count': 3,
  'lead_score': 0.38},
 {'lead_source': 'organic_search',
  'industry': 'retail',
  'employment_status': 'student',
  'location': 'europe',
  'annual_income': 0.0,
  'number_of_courses_viewed': 3,
  'interaction_count': 8,
  'lead_score': 0.62},
 {'lead_source': 'organic_search',
  'industry': 'technology',
  'employment_status': 'employed',
  'location': 'south_america',
  'annual_income': 63847.0,
  'number_of_courses_viewed': 0,
  'interaction_count': 1,
  'lead_score': 0.31},
 {'lead_source': 'organic_search',
  'industry': 'technology',
  'employment_status': 'employed',
  'location': 'north_america',
  'annual_income': 102844.0,
  'number_of_courses_viewed': 1,
  'interaction_count': 5,
  'lead_score': 0.55},
 {'lead_source': 'events',
  'industry': 'retail',
  'employment_status': 'employed',
  'location': 'NA',
  'annual_income': 48752.0,
  'number_of_courses_viewed': 3,
  'interaction_count': 7,
  'lead_score': 0.59},
 {'lead_source': 'organic_search',
  'industry': 'manufacturing',
  'employment_status': 'self_employed',
  'location': 'europe',
  'annual_income': 63101.0,
  'number_of_courses_viewed': 1,
  'interaction_count': 5,
  'lead_score': 0.59},
 {'lead_source': 'social_media',
  'industry': 'manufacturing',
  'employment_status': 'employed',
  'location': 'europe',
  'annual_income': 54204.0,
  'number_of_courses_viewed': 2,
  'interaction_count': 7,
  'lead_score': 0.68},
 {'lead_source': 'organic_search',
  'industry': 'healthcare',
  'employment_status': 'self_employed',
  'location': 'north_america',
  'annual_income': 69027.0,
  'number_of_courses_viewed': 2,
  'interaction_count': 7,
  'lead_score': 0.7},
 {'lead_source': 'referral',
  'industry': 'education',
  'employment_status': 'self_employed',
  'location': 'south_america',
  'annual_income': 30572.0,
  'number_of_courses_viewed': 3,
  'interaction_count': 7,
  'lead_score': 0.76},
 {'lead_source': 'referral',
  'industry': 'education',
  'employment_status': 'student',
  'location': 'south_america',
  'annual_income': 12000.0,
  'number_of_courses_viewed': 2,
  'interaction_count': 7,
  'lead_score': 0.64},
 {'lead_source': 'events',
  'industry': 'healthcare',
  'employment_status': 'self_employed',
  'location': 'north_america',
  'annual_income': 66834.0,
  'number_of_courses_viewed': 2,
  'interaction_count': 2,
  'lead_score': 0.4},
 {'lead_source': 'events',
  'industry': 'retail',
  'employment_status': 'NA',
  'location': 'north_america',
  'annual_income': 52517.0,
  'number_of_courses_viewed': 1,
  'interaction_count': 8,
  'lead_score': 0.72},
 {'lead_source': 'referral',
  'industry': 'healthcare',
  'employment_status': 'student',
  'location': 'asia',
  'annual_income': 12000.0,
  'number_of_courses_viewed': 2,
  'interaction_count': 6,
  'lead_score': 0.63},
 {'lead_source': 'social_media',
  'industry': 'finance',
  'employment_status': 'student',
  'location': 'north_america',
  'annual_income': 0.0,
  'number_of_courses_viewed': 0,
  'interaction_count': 3,
  'lead_score': 0.33},
 {'lead_source': 'paid_ads',
  'industry': 'healthcare',
  'employment_status': 'employed',
  'location': 'asia',
  'annual_income': 64886.0,
  'number_of_courses_viewed': 0,
  'interaction_count': 1,
  'lead_score': 0.19},
 {'lead_source': 'events',
  'industry': 'healthcare',
  'employment_status': 'employed',
  'location': 'north_america',
  'annual_income': 66682.0,
  'number_of_courses_viewed': 0,
  'interaction_count': 2,
  'lead_score': 0.31},
 {'lead_source': 'paid_ads',
  'industry': 'healthcare',
  'employment_status': 'employed',
  'location': 'south_america',
  'annual_income': 64647.0,
  'number_of_courses_viewed': 1,
  'interaction_count': 3,
  'lead_score': 0.37},
 {'lead_source': 'organic_search',
  'industry': 'manufacturing',
  'employment_status': 'unemployed',
  'location': 'europe',
  'annual_income': 0.0,
  'number_of_courses_viewed': 2,
  'interaction_count': 3,
  'lead_score': 0.43},
 {'lead_source': 'NA',
  'industry': 'retail',
  'employment_status': 'NA',
  'location': 'europe',
  'annual_income': 38652.0,
  'number_of_courses_viewed': 1,
  'interaction_count': 2,
  'lead_score': 0.3},
 {'lead_source': 'events',
  'industry': 'retail',
  'employment_status': 'employed',
  'location': 'NA',
  'annual_income': 51641.0,
  'number_of_courses_viewed': 1,
  'interaction_count': 2,
  'lead_score': 0.3},
 {'lead_source': 'paid_ads',
  'industry': 'retail',
  'employment_status': 'employed',
  'location': 'north_america',
  'annual_income': 55999.0,
  'number_of_courses_viewed': 2,
  'interaction_count': 4,
  'lead_score': 0.41},
 {'lead_source': 'events',
  'industry': 'technology',
  'employment_status': 'unemployed',
  'location': 'south_america',
  'annual_income': 43295.0,
  'number_of_courses_viewed': 0,
  'interaction_count': 2,
  'lead_score': 0.32},
 {'lead_source': 'referral',
  'industry': 'technology',
  'employment_status': 'employed',
  'location': 'south_america',
  'annual_income': 76629.0,
  'number_of_courses_viewed': 2,
  'interaction_count': 4,
  'lead_score': 0.49},
 {'lead_source': 'organic_search',
  'industry': 'healthcare',
  'employment_status': 'employed',
  'location': 'europe',
  'annual_income': 55812.0,
  'number_of_courses_viewed': 3,
  'interaction_count': 4,
  'lead_score': 0.61},
 {'lead_source': 'paid_ads',
  'industry': 'education',
  'employment_status': 'unemployed',
  'location': 'north_america',
  'annual_income': 27290.0,
  'number_of_courses_viewed': 2,
  'interaction_count': 3,
  'lead_score': 0.33},
 {'lead_source': 'organic_search',
  'industry': 'healthcare',
  'employment_status': 'self_employed',
  'location': 'north_america',
  'annual_income': 60001.0,
  'number_of_courses_viewed': 2,
  'interaction_count': 6,
  'lead_score': 0.69},
 {'lead_source': 'organic_search',
  'industry': 'healthcare',
  'employment_status': 'employed',
  'location': 'south_america',
  'annual_income': 62067.0,
  'number_of_courses_viewed': 2,
  'interaction_count': 4,
  'lead_score': 0.46},
 {'lead_source': 'events',
  'industry': 'manufacturing',
  'employment_status': 'unemployed',
  'location': 'NA',
  'annual_income': 37688.0,
  'number_of_courses_viewed': 1,
  'interaction_count': 2,
  'lead_score': 0.2},
 {'lead_source': 'paid_ads',
  'industry': 'technology',
  'employment_status': 'employed',
  'location': 'africa',
  'annual_income': 86753.0,
  'number_of_courses_viewed': 3,
  'interaction_count': 2,
  'lead_score': 0.37},
 {'lead_source': 'paid_ads',
  'industry': 'finance',
  'employment_status': 'self_employed',
  'location': 'asia',
  'annual_income': 68915.0,
  'number_of_courses_viewed': 2,
  'interaction_count': 3,
  'lead_score': 0.37},
 {'lead_source': 'paid_ads',
  'industry': 'technology',
  'employment_status': 'unemployed',
  'location': 'asia',
  'annual_income': 0.0,
  'number_of_courses_viewed': 1,
  'interaction_count': 0,
  'lead_score': 0.09},
 {'lead_source': 'social_media',
  'industry': 'technology',
  'employment_status': 'student',
  'location': 'north_america',
  'annual_income': 42114.0,
  'number_of_courses_viewed': 1,
  'interaction_count': 4,
  'lead_score': 0.35},
 {'lead_source': 'organic_search',
  'industry': 'retail',
  'employment_status': 'employed',
  'location': 'north_america',
  'annual_income': 53635.0,
  'number_of_courses_viewed': 3,
  'interaction_count': 7,
  'lead_score': 0.64},
 {'lead_source': 'events',
  'industry': 'technology',
  'employment_status': 'employed',
  'location': 'north_america',
  'annual_income': 80003.0,
  'number_of_courses_viewed': 1,
  'interaction_count': 0,
  'lead_score': 0.2},
 {'lead_source': 'referral',
  'industry': 'technology',
  'employment_status': 'student',
  'location': 'NA',
  'annual_income': 37131.0,
  'number_of_courses_viewed': 3,
  'interaction_count': 5,
  'lead_score': 0.6},
 {'lead_source': 'events',
  'industry': 'technology',
  'employment_status': 'employed',
  'location': 'europe',
  'annual_income': 86306.0,
  'number_of_courses_viewed': 3,
  'interaction_count': 7,
  'lead_score': 0.53},
 {'lead_source': 'organic_search',
  'industry': 'manufacturing',
  'employment_status': 'employed',
  'location': 'asia',
  'annual_income': 47434.0,
  'number_of_courses_viewed': 1,
  'interaction_count': 4,
  'lead_score': 0.39},
 {'lead_source': 'organic_search',
  'industry': 'NA',
  'employment_status': 'unemployed',
  'location': 'north_america',
  'annual_income': 69280.0,
  'number_of_courses_viewed': 4,
  'interaction_count': 6,
  'lead_score': 0.74},
 {'lead_source': 'organic_search',
  'industry': 'technology',
  'employment_status': 'self_employed',
  'location': 'africa',
  'annual_income': 63247.0,
  'number_of_courses_viewed': 4,
  'interaction_count': 9,
  'lead_score': 0.81},
 {'lead_source': 'social_media',
  'industry': 'healthcare',
  'employment_status': 'self_employed',
  'location': 'europe',
  'annual_income': 67887.0,
  'number_of_courses_viewed': 3,
  'interaction_count': 5,
  'lead_score': 0.58},
 {'lead_source': 'organic_search',
  'industry': 'technology',
  'employment_status': 'student',
  'location': 'NA',
  'annual_income': 0.0,
  'number_of_courses_viewed': 2,
  'interaction_count': 9,
  'lead_score': 0.8},
 {'lead_source': 'social_media',
  'industry': 'finance',
  'employment_status': 'employed',
  'location': 'asia',
  'annual_income': 81312.0,
  'number_of_courses_viewed': 1,
  'interaction_count': 4,
  'lead_score': 0.5},
 {'lead_source': 'organic_search',
  'industry': 'healthcare',
  'employment_status': 'employed',
  'location': 'asia',
  'annual_income': 55591.0,
  'number_of_courses_viewed': 2,
  'interaction_count': 8,
  'lead_score': 0.7},
 {'lead_source': 'social_media',
  'industry': 'technology',
  'employment_status': 'self_employed',
  'location': 'europe',
  'annual_income': 67240.0,
  'number_of_courses_viewed': 1,
  'interaction_count': 1,
  'lead_score': 0.3},
 {'lead_source': 'referral',
  'industry': 'healthcare',
  'employment_status': 'employed',
  'location': 'south_america',
  'annual_income': 56085.0,
  'number_of_courses_viewed': 4,
  'interaction_count': 10,
  'lead_score': 0.9},
 {'lead_source': 'organic_search',
  'industry': 'retail',
  'employment_status': 'employed',
  'location': 'south_america',
  'annual_income': 49635.0,
  'number_of_courses_viewed': 4,
  'interaction_count': 9,
  'lead_score': 0.75},
 {'lead_source': 'referral',
  'industry': 'education',
  'employment_status': 'student',
  'location': 'north_america',
  'annual_income': 0.0,
  'number_of_courses_viewed': 4,
  'interaction_count': 8,
  'lead_score': 0.76},
 {'lead_source': 'social_media',
  'industry': 'manufacturing',
  'employment_status': 'employed',
  'location': 'africa',
  'annual_income': 46549.0,
  'number_of_courses_viewed': 0,
  'interaction_count': 3,
  'lead_score': 0.34},
 {'lead_source': 'organic_search',
  'industry': 'education',
  'employment_status': 'employed',
  'location': 'south_america',
  'annual_income': 49683.0,
  'number_of_courses_viewed': 2,
  'interaction_count': 4,
  'lead_score': 0.43},
 {'lead_source': 'organic_search',
  'industry': 'finance',
  'employment_status': 'employed',
  'location': 'africa',
  'annual_income': 54830.0,
  'number_of_courses_viewed': 1,
  'interaction_count': 4,
  'lead_score': 0.51},
 {'lead_source': 'organic_search',
  'industry': 'retail',
  'employment_status': 'student',
  'location': 'asia',
  'annual_income': 12000.0,
  'number_of_courses_viewed': 3,
  'interaction_count': 7,
  'lead_score': 0.66},
 {'lead_source': 'organic_search',
  'industry': 'healthcare',
  'employment_status': 'student',
  'location': 'north_america',
  'annual_income': 0.0,
  'number_of_courses_viewed': 0,
  'interaction_count': 2,
  'lead_score': 0.27},
 {'lead_source': 'referral',
  'industry': 'finance',
  'employment_status': 'employed',
  'location': 'europe',
  'annual_income': 64679.0,
  'number_of_courses_viewed': 3,
  'interaction_count': 7,
  'lead_score': 0.76},
 {'lead_source': 'social_media',
  'industry': 'technology',
  'employment_status': 'student',
  'location': 'north_america',
  'annual_income': 0.0,
  'number_of_courses_viewed': 0,
  'interaction_count': 0,
  'lead_score': 0.17},
 {'lead_source': 'organic_search',
  'industry': 'finance',
  'employment_status': 'self_employed',
  'location': 'north_america',
  'annual_income': 77879.0,
  'number_of_courses_viewed': 3,
  'interaction_count': 6,
  'lead_score': 0.66},
 {'lead_source': 'organic_search',
  'industry': 'education',
  'employment_status': 'employed',
  'location': 'asia',
  'annual_income': 37344.0,
  'number_of_courses_viewed': 2,
  'interaction_count': 2,
  'lead_score': 0.27},
 {'lead_source': 'social_media',
  'industry': 'retail',
  'employment_status': 'unemployed',
  'location': 'north_america',
  'annual_income': 19707.0,
  'number_of_courses_viewed': 2,
  'interaction_count': 4,
  'lead_score': 0.52},
 {'lead_source': 'events',
  'industry': 'manufacturing',
  'employment_status': 'NA',
  'location': 'south_america',
  'annual_income': 42349.0,
  'number_of_courses_viewed': 4,
  'interaction_count': 7,
  'lead_score': 0.72},
 {'lead_source': 'organic_search',
  'industry': 'finance',
  'employment_status': 'employed',
  'location': 'north_america',
  'annual_income': 78551.0,
  'number_of_courses_viewed': 2,
  'interaction_count': 6,
  'lead_score': 0.63},
 {'lead_source': 'events',
  'industry': 'healthcare',
  'employment_status': 'self_employed',
  'location': 'asia',
  'annual_income': 58408.0,
  'number_of_courses_viewed': 2,
  'interaction_count': 5,
  'lead_score': 0.62},
 {'lead_source': 'referral',
  'industry': 'education',
  'employment_status': 'employed',
  'location': 'europe',
  'annual_income': 31392.0,
  'number_of_courses_viewed': 3,
  'interaction_count': 4,
  'lead_score': 0.52},
 {'lead_source': 'events',
  'industry': 'finance',
  'employment_status': 'employed',
  'location': 'europe',
  'annual_income': 72673.0,
  'number_of_courses_viewed': 3,
  'interaction_count': 3,
  'lead_score': 0.0},
 {'lead_source': 'paid_ads',
  'industry': 'retail',
  'employment_status': 'self_employed',
  'location': 'asia',
  'annual_income': 44715.0,
  'number_of_courses_viewed': 3,
  'interaction_count': 9,
  'lead_score': 0.76},
 {'lead_source': 'referral',
  'industry': 'education',
  'employment_status': 'student',
  'location': 'north_america',
  'annual_income': 0.0,
  'number_of_courses_viewed': 0,
  'interaction_count': 3,
  'lead_score': 0.3},
 {'lead_source': 'social_media',
  'industry': 'technology',
  'employment_status': 'self_employed',
  'location': 'south_america',
  'annual_income': 76345.0,
  'number_of_courses_viewed': 1,
  'interaction_count': 4,
  'lead_score': 0.49},
 {'lead_source': 'events',
  'industry': 'finance',
  'employment_status': 'employed',
  'location': 'africa',
  'annual_income': 60520.0,
  'number_of_courses_viewed': 2,
  'interaction_count': 4,
  'lead_score': 0.43},
 {'lead_source': 'organic_search',
  'industry': 'retail',
  'employment_status': 'employed',
  'location': 'africa',
  'annual_income': 47808.0,
  'number_of_courses_viewed': 3,
  'interaction_count': 5,
  'lead_score': 0.54},
 {'lead_source': 'events',
  'industry': 'education',
  'employment_status': 'self_employed',
  'location': 'asia',
  'annual_income': 32952.0,
  'number_of_courses_viewed': 2,
  'interaction_count': 4,
  'lead_score': 0.0},
 {'lead_source': 'organic_search',
  'industry': 'manufacturing',
  'employment_status': 'employed',
  'location': 'asia',
  'annual_income': 62477.0,
  'number_of_courses_viewed': 4,
  'interaction_count': 11,
  'lead_score': 0.99},
 {'lead_source': 'paid_ads',
  'industry': 'technology',
  'employment_status': 'employed',
  'location': 'south_america',
  'annual_income': 58664.0,
  'number_of_courses_viewed': 1,
  'interaction_count': 5,
  'lead_score': 0.41},
 {'lead_source': 'paid_ads',
  'industry': 'finance',
  'employment_status': 'student',
  'location': 'europe',
  'annual_income': 41083.0,
  'number_of_courses_viewed': 3,
  'interaction_count': 3,
  'lead_score': 0.34},
 {'lead_source': 'social_media',
  'industry': 'retail',
  'employment_status': 'unemployed',
  'location': 'europe',
  'annual_income': 18663.0,
  'number_of_courses_viewed': 1,
  'interaction_count': 4,
  'lead_score': 0.3},
 {'lead_source': 'events',
  'industry': 'retail',
  'employment_status': 'student',
  'location': 'asia',
  'annual_income': 12000.0,
  'number_of_courses_viewed': 2,
  'interaction_count': 3,
  'lead_score': 0.33},
 {'lead_source': 'organic_search',
  'industry': 'finance',
  'employment_status': 'employed',
  'location': 'north_america',
  'annual_income': 84157.0,
  'number_of_courses_viewed': 2,
  'interaction_count': 2,
  'lead_score': 0.36},
 {'lead_source': 'paid_ads',
  'industry': 'finance',
  'employment_status': 'NA',
  'location': 'south_america',
  'annual_income': 38591.0,
  'number_of_courses_viewed': 0,
  'interaction_count': 1,
  'lead_score': 0.14},
 {'lead_source': 'social_media',
  'industry': 'NA',
  'employment_status': 'employed',
  'location': 'europe',
  'annual_income': 79824.0,
  'number_of_courses_viewed': 2,
  'interaction_count': 1,
  'lead_score': 0.37},
 {'lead_source': 'social_media',
  'industry': 'technology',
  'employment_status': 'employed',
  'location': 'north_america',
  'annual_income': 88591.0,
  'number_of_courses_viewed': 4,
  'interaction_count': 7,
  'lead_score': 0.81},
 {'lead_source': 'social_media',
  'industry': 'manufacturing',
  'employment_status': 'employed',
  'location': 'africa',
  'annual_income': 45529.0,
  'number_of_courses_viewed': 4,
  'interaction_count': 8,
  'lead_score': 0.69},
 {'lead_source': 'social_media',
  'industry': 'finance',
  'employment_status': 'employed',
  'location': 'europe',
  'annual_income': 67429.0,
  'number_of_courses_viewed': 3,
  'interaction_count': 6,
  'lead_score': 0.65},
 {'lead_source': 'referral',
  'industry': 'technology',
  'employment_status': 'employed',
  'location': 'europe',
  'annual_income': 73625.0,
  'number_of_courses_viewed': 3,
  'interaction_count': 7,
  'lead_score': 0.75},
 {'lead_source': 'paid_ads',
  'industry': 'finance',
  'employment_status': 'employed',
  'location': 'north_america',
  'annual_income': 80755.0,
  'number_of_courses_viewed': 1,
  'interaction_count': 2,
  'lead_score': 0.39},
 {'lead_source': 'paid_ads',
  'industry': 'technology',
  'employment_status': 'employed',
  'location': 'north_america',
  'annual_income': 102342.0,
  'number_of_courses_viewed': 2,
  'interaction_count': 6,
  'lead_score': 0.68},
 {'lead_source': 'referral',

In [108]:
dv = DictVectorizer(sparse=False)
X_train = dv.fit_transform(df_train_dicts)
X_train

array([[6.5980e+04, 0.0000e+00, 1.0000e+00, ..., 0.0000e+00, 0.0000e+00,
        2.0000e+00],
       [7.1662e+04, 0.0000e+00, 1.0000e+00, ..., 0.0000e+00, 1.0000e+00,
        0.0000e+00],
       [4.0220e+04, 0.0000e+00, 1.0000e+00, ..., 0.0000e+00, 0.0000e+00,
        2.0000e+00],
       ...,
       [7.1532e+04, 0.0000e+00, 1.0000e+00, ..., 0.0000e+00, 0.0000e+00,
        3.0000e+00],
       [4.8836e+04, 0.0000e+00, 1.0000e+00, ..., 0.0000e+00, 0.0000e+00,
        0.0000e+00],
       [6.8969e+04, 0.0000e+00, 1.0000e+00, ..., 0.0000e+00, 0.0000e+00,
        0.0000e+00]], shape=(3000, 28))

In [109]:
model = LogisticRegression(solver="liblinear", C=1.0, max_iter=1000, random_state=42)
model.fit(X_train, y_train)

LogisticRegression(max_iter=1000, random_state=42, solver='liblinear')

In [113]:
df_val_dicts = df_val[categorical + numerical].to_dict(orient="records")
X_val = dv.transform(df_val_dicts)
X_val

array([[8.0457e+04, 0.0000e+00, 1.0000e+00, ..., 0.0000e+00, 0.0000e+00,
        3.0000e+00],
       [7.4480e+04, 0.0000e+00, 0.0000e+00, ..., 0.0000e+00, 0.0000e+00,
        0.0000e+00],
       [4.3944e+04, 0.0000e+00, 0.0000e+00, ..., 0.0000e+00, 0.0000e+00,
        2.0000e+00],
       ...,
       [6.2439e+04, 0.0000e+00, 0.0000e+00, ..., 0.0000e+00, 0.0000e+00,
        0.0000e+00],
       [4.0878e+04, 0.0000e+00, 0.0000e+00, ..., 1.0000e+00, 0.0000e+00,
        1.0000e+00],
       [4.8769e+04, 0.0000e+00, 1.0000e+00, ..., 0.0000e+00, 0.0000e+00,
        3.0000e+00]], shape=(1000, 28))

In [ ]:
y_pred = model.predict_proba(X_val)[:, 1]
convert_desicion = (y_pred >= 0.5).astype(int)

array([1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1,
       1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1,
       0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1,
       1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0,
       1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1,
       1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1,
       1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0,
       1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1,
       1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 1, 1])

In [120]:
accuracy = (convert_desicion == y_val).mean()
round(accuracy, 2)

np.float64(0.64)

In [144]:
accuracy

np.float64(0.645)

Answer: 0.65

## Question 5

In [143]:
diffs = {}

for c in df_train.columns:
    df_no_feature_train = df_train.drop(columns=[c])

    df_no_feature_train_dict = df_no_feature_train.to_dict(orient="records")
    X_no_feature_train = dv.transform(df_no_feature_train_dict)

    model_no_feature = LogisticRegression(
        solver="liblinear", C=1.0, max_iter=1000, random_state=42
    )
    model_no_feature.fit(X_no_feature_train, y_train)

    y_pred = model_no_feature.predict_proba(X_val)[:, 1]
    convert_desicion_no_feature = (y_pred >= 0.5).astype(int)

    acc = (convert_desicion_no_feature == y_val).mean()
    diffs[c] = accuracy - acc

pd.Series(diffs)

lead_source                 0.003
industry                    0.000
employment_status           0.000
location                    0.000
annual_income              -0.079
number_of_courses_viewed    0.002
interaction_count           0.044
lead_score                  0.001
dtype: float64

Answer: number_of_courses_viewed

## Question 6

In [142]:
C_test = [0.000001, 0.00001, 0.0001, 0.001]
accs = {}

for c in C_test:
    model_reg = LogisticRegression(
        solver="liblinear", C=c, max_iter=1000, random_state=42
    )
    model_reg.fit(X_train, y_train)

    y_pred = model_reg.predict_proba(X_val)[:, 1]
    convert_desicion_reg = y_pred >= 0.5

    accs[c] = (convert_desicion_reg == y_val).mean()

pd.Series(accs).sort_values(ascending=False)

0.001000    0.645
0.000100    0.613
0.000010    0.598
0.000001    0.598
dtype: float64

Answer: 0.001